name: CI/CD for BlogAPI spring Boot

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: '21'
      - name: Build with Maven
        run: mvn clean package install -DskipTests
      - name: Login to docker hub
        run: docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_PASSWORD}}
      - name: Create .env file from PROD_ENV_FILE secret
        run: echo "${{ secrets.PROD_ENV_FILE }}" > .env
      - name: Build docker image
        run: docker build -t nhatanh2708/blog-app-api:latest -f Dockerfile .
      - name: Publish image to docker hub
        run: docker push nhatanh2708/blog-app-api:latest

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Pull Image from docker hub
        run: docker pull nhatanh2708/blog-app-api:latest
      - name: Delete old container
        run: docker rm -f blog-api
      - name: Run docker container
        run: docker run -d -p 8080:8080 --name blog-api nhatanh2708/blog-app-api
      - name: Connect SSH and Restart Services
        run: sudo systemctl restart nginx
